'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'EN' | 'GE' | 'RU';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    // Navigation
    collections: 'Collections',
    our_story: 'Our Story',
    shop_the_look: 'Shop The Look',
    visit_us: 'Visit Us',
    call_us: 'Call Us',
    shopping_cart: 'Shopping Cart',

    // Hero
    handcrafted_luxury: 'Handcrafted Luxury',
    hero_title: 'VELLUTO',
    hero_subtitle: 'The Art of Fine Craftsmanship',
    hero_desc:
      'Discover curated collections of timeless luxury fashion and premium garments designed to complement your elegance.',
    explore_collection: 'Explore Collection',
    shop_look: 'Shop the Look',

    // Editorial Intro
    heritage_title: 'THE HERITAGE',
    heritage_subtitle: 'Sculpted by Heritage, Refined for Today',
    heritage_desc1:
      'Born from a lineage of Georgian master tailors, Velluto blends ancestral sartorial techniques with contemporary high-fashion geometry. Every piece is hand-tailored in our Tbilisi workshop using ethically sourced premium fabrics.',
    heritage_desc2:
      'We believe fashion is not an accessory, but a physical extension of your character. A silent dialogue between form, premium fabrics, and design.',
    stats_years: '12+',
    stats_years_label: 'Years of Artistry',
    stats_items: '5,000+',
    stats_items_label: 'Handmade Creations',

    // Editorial Strip
    strip_title: 'Aesthetic Statement',
    strip_subtitle: '"Beauty begins the moment you decide to be yourself."',
    strip_collection: 'The Signature Collection',

    // New Arrivals
    new_arrivals: 'New Arrivals',
    arrivals_subtitle: 'Hand-selected signature pieces from our latest workshop release',
    add_to_cart: 'Add to Cart',
    in_cart: 'In Cart',
    gel: 'GEL',

    // Products
    product_ring_title: 'Velluto Gold Signet Ring',
    product_ring_desc:
      'Hand-engraved 18k yellow gold signet ring featuring clean geometric facets.',
    product_bracelet_title: 'Luxury Faceted Gold Bracelet',
    product_bracelet_desc:
      'Polished solid gold interlocking links, structured to catch the light at every angle.',
    product_earrings_title: 'Diamond Halo Stud Earrings',
    product_earrings_desc:
      'Brilliant-cut VS1 diamonds claw-set in an architectural 18k white gold housing.',

    // Shop the Look
    shop_look_title: 'Shop the Look',
    shop_look_subtitle: 'Hover over the gold hotspots to inspect and shop the look',
    spot_ring: 'Velluto Gold Signet Ring — 2,400 GEL',
    spot_bracelet: 'Luxury Faceted Gold Bracelet — 3,800 GEL',
    spot_earrings: 'Diamond Halo Stud Earrings — 1,950 GEL',

    // Instagram
    insta_title: 'Editorial Showcase',
    insta_subtitle: 'Follow our journey and daily inspirations on Instagram @velluto_____',

    // Location
    visit_us_title: 'Visit Our Boutique',
    visit_us_desc:
      'Our showroom is nestled in the historic district of Tbilisi. Experience the collections in person, receive custom sizing consultations, and preview unreleased collections.',
    address_label: 'Address',
    address_value: 'Vardisubani, Tbilisi, Georgia',
    phone_label: 'Phone',
    hours_label: 'Hours',
    hours_value: 'Open 24/7 · Mon - Sun (Appointments recommended)',
    open_maps: 'Open in Google Maps',

    // Footer
    footer_desc:
      'Exclusive handcrafted fashion and premium apparel designed to elevate your personal style. Created with luxury materials and meticulous craftsmanship.',
    footer_copyright: 'All rights reserved.',

    // Mini Cart
    cart_title: 'Your Selection',
    cart_empty: 'Your cart is empty',
    cart_subtotal: 'Subtotal',
    cart_checkout: 'Proceed to Checkout',

    // Checkout
    checkout_title: 'Secure Checkout',
    checkout_subtitle: 'Finalize your luxury selection and complete your order via WhatsApp',
    billing_details: 'Boutique Delivery Details',
    full_name: 'Full Name',
    phone_number: 'Phone Number',
    order_notes: 'Special Requests / Sizing Notes',
    notes_placeholder: 'E.g., Suit/dress sizing adjustments, preferred fit details...',
    summary: 'Order Summary',
    items_total: 'Items Total',
    delivery: 'Delivery',
    free: 'Free',
    total_due: 'Total Due',
    complete_whatsapp: 'Complete Order via WhatsApp',
    whatsapp_error: 'Please fill in your name and phone number.',
    back_to_shop: 'Back to Shop',

    // Admin Panel
    admin_dashboard: 'Dashboard',
    admin_products: 'Products',
    admin_orders: 'Orders',
    admin_customers: 'Customers',
    admin_content: 'Content Editor',
    admin_media: 'Media Library',
    admin_marketing: 'Marketing',
    admin_analytics: 'Analytics',
    admin_notifications: 'Notifications',
    admin_settings: 'Settings',
    admin_logout: 'Logout',
    admin_view_storefront: 'View Storefront',
    admin_super_admin: 'Super Admin',
    admin_new_product_title: 'Add New Product',
    admin_new_product_subtitle: 'Define pricing, description, variants, and SEO meta',
    admin_cancel: 'Cancel',
    admin_add_product: 'Add Product',
    admin_saving: 'Saving...',
    admin_prod_translations: 'Product Translations',
    admin_prod_name_en: 'Product Name (EN) *',
    admin_prod_name_ka: 'Product Name (KA) *',
    admin_prod_name_ru: 'Product Name (RU) *',
    admin_desc_en: 'Description (EN)',
    admin_desc_ka: 'Description (KA)',
    admin_desc_ru: 'Description (RU)',
    admin_pricing_logistics: 'Pricing & Logistics',
    admin_base_price: 'Base Price (GEL) *',
    admin_sku: 'SKU Code *',
    admin_inventory: 'Inventory Stock level',
    admin_variants_title: 'Product Variants',
    admin_add_variant: 'Add Variant',
    admin_no_variants: 'No variants defined. Add size or color choices if applicable.',
    admin_variant_sku: 'Variant SKU',
    admin_size: 'Size',
    admin_color: 'Color',
    admin_stock: 'Stock',
    admin_price_adj: 'Price Adj (+/-)',
    admin_gallery_title: 'Image Gallery',
    admin_gallery_subtitle: 'Select one or more catalog assets stored in your media vault',
    admin_upload_image: 'Upload Image',
    admin_uploading: 'Uploading...',
    admin_no_images: 'No images uploaded in Media Library yet.',
    admin_status_tax: 'Status & Taxonomy',
    admin_prod_id: 'Product ID (optional)',
    admin_category: 'Store Category *',
    admin_visibility: 'Visibility Status',
    admin_promo_tag: 'Promotional Tag',
    admin_initial_rating: 'Initial Star Rating',
    admin_seo_config: 'SEO Configurations',
    admin_seo_title: 'SEO Meta Title',
    admin_seo_desc: 'SEO Meta Description',
    
    // Admin Dashboard
    admin_dashboard_loading: 'Loading Dashboard Metrics...',
    admin_dashboard_retry: 'Retry',
    admin_dashboard_overview: 'Overview',
    admin_dashboard_subtitle: 'Store activities and metric charts',
    admin_dashboard_refresh: 'Refresh',
    admin_stat_revenue: 'Total Revenue',
    admin_stat_orders: 'Orders Completed',
    admin_stat_aov: 'Average Order Value',
    admin_stat_low_stock: 'Low Stock Alerts',
    admin_chart_title: 'Monthly Sales Analytics',
    admin_chart_subtitle: 'Revenue generation timeline',
    admin_chart_rendering: 'Rendering Chart...',
    admin_recent_orders: 'Recent Orders',
    admin_recent_orders_sub: 'Latest incoming catalog sales',
    admin_view_all_orders: 'View All Orders →',
    admin_table_id: 'ID',
    admin_table_customer: 'Customer',
    admin_table_payment: 'Payment',
    admin_table_status: 'Status',
    admin_table_total: 'Total',
    admin_no_recent_orders: 'No recent orders.',
    admin_best_sellers: 'Best Selling Products',
    admin_best_sellers_sub: 'Top sales item performance',
    admin_no_sales: 'No sales recorded yet.',
    admin_qty_sold: 'Quantity sold: ',
    admin_low_stock_warning: 'Low Stock Warning',
    admin_low_stock_sub: 'Items requiring inventory refill',
    admin_all_inventory_healthy: 'All inventory levels healthy.',
    admin_left: 'left',
    
    // Admin Products List
    admin_products_loading: 'Loading Products Catalog...',
    admin_products_title: 'Product Catalog',
    admin_products_subtitle: 'Browse, search, edit, and duplicate products',
    admin_products_add: 'Add Product',
    admin_products_search: 'Search products by title, SKU code...',
    admin_products_empty: 'No products found in database catalog. Try seeding or adding new items.',
    admin_products_image: 'Image',
    admin_products_name_sku: 'Name & SKU',
    admin_products_category: 'Category',
    admin_products_price: 'Price',
    admin_products_inventory: 'Inventory',
    admin_products_status: 'Status',
    admin_products_actions: 'Actions',
    admin_out_of_stock: 'Out of Stock',
    admin_units: 'units',
    admin_product_dupe_success: 'Product duplicated successfully.',
    admin_product_dupe_fail: 'Failed to duplicate product.',
    admin_product_del_confirm: 'Are you sure you want to delete this product? This will remove all variants and images.',
    admin_product_del_success: 'Product deleted successfully.',
    admin_product_del_fail: 'Failed to delete product.',

    // Edit Product
    admin_edit_product_title: 'Edit Product',
    admin_edit_product_subtitle_staff: 'Limited management mode (Update inventory only)',
    admin_edit_product_subtitle_admin: 'Modify metadata and taxonomy for SKU: ',
    admin_edit_product_loading: 'Loading Product details...',
    admin_edit_product_not_found: 'Product details could not be found.',
    admin_edit_product_success: 'Product updated successfully.',
    admin_edit_product_fail: 'Failed to update product details.',
    admin_save_changes: 'Save Changes',

    // Orders List
    admin_orders_loading: 'Loading Orders Log...',
    admin_orders_no_export: 'No orders available to export.',
    admin_orders_col_id: 'Order ID',
    admin_orders_col_customer: 'Customer Details',
    admin_orders_col_phone: 'Phone',
    admin_orders_col_address: 'Address',
    admin_orders_col_date: 'Delivery Date',
    admin_orders_col_time: 'Delivery Time',
    admin_orders_col_method: 'Method',
    admin_orders_col_status: 'Order Status',
    admin_orders_col_pay_status: 'Payment Status',
    admin_orders_col_total: 'Total Price',
    admin_orders_col_items: 'Ordered Items',
    admin_orders_filter_all_status: 'All Order Statuses',
    admin_orders_filter_pending: 'Pending',
    admin_orders_filter_processing: 'Processing',
    admin_orders_filter_shipped: 'Shipped',
    admin_orders_filter_delivered: 'Delivered',
    admin_orders_filter_cancelled: 'Cancelled',
    admin_orders_filter_refunded: 'Refunded',
    admin_orders_filter_all_pay: 'All Payment Methods',
    admin_orders_filter_cash: 'Cash',
    admin_orders_filter_card: 'Card',
    admin_orders_filter_bank: 'Bank',
    admin_orders_title: 'Orders Log',
    admin_orders_subtitle: 'Track sales status, payments, and export transaction tables',
    admin_orders_export: 'Export CSV',
    admin_orders_search: 'Search orders by customer name, order ID, phone...',
    admin_orders_empty: 'No orders matched the filter criteria.',

    // Order Details
    admin_order_not_found: 'Order details could not be found.',
    admin_order_update_success: 'Order updated successfully.',
    admin_order_update_fail: 'Failed to update order.',
    admin_order_loading: 'Loading Order Profile...',
    admin_order_title: 'Order Details',
    admin_order_subtitle: 'Manage client delivery profiles, status transitions, and issue invoices',
    admin_order_view_invoice: 'View Invoice',
    admin_order_back: 'Back to List',
    admin_order_items: 'Ordered Items',
    admin_order_options: 'Selected options: ',
    admin_order_qty: 'Quantity: x',
    admin_order_subtotal: 'Subtotal',
    admin_order_discount: 'Discount Code',
    admin_order_vat: 'VAT (18% Included)',
    admin_order_grand_total: 'Grand Total',
    admin_order_notes: 'Gift Note / Notes',
    admin_order_no_notes: 'No custom note requests added to this order.',
    admin_order_actions: 'Log Status Actions',
    admin_order_status_label: 'Order Status',
    admin_order_payment_label: 'Payment Status',
    admin_order_unpaid: 'Unpaid',
    admin_order_paid: 'Paid',
    admin_order_updating: 'Updating Log...',
    admin_order_update_btn: 'Update Log Status',
    admin_order_client: 'Client Profile',
    admin_order_name: 'Name',
    admin_order_phone: 'Phone',
    admin_order_delivery_address: 'Delivery Address',
    admin_order_delivery_schedule: 'Delivery Schedule',
    admin_order_payment_option: 'Payment Option',
    admin_invoice_print: 'Print Invoice',
    admin_invoice_title: 'Invoice',
    admin_invoice_billed_to: 'Billed To:',
    admin_invoice_boutique: 'Boutique Details:',
    admin_invoice_item_name: 'Item Name',
    admin_invoice_variant_det: 'Variant Details',
    admin_invoice_unit_price: 'Unit Price',
    admin_invoice_coupon: 'Coupon',

    // Customers List
    admin_customers_update_success: 'Customer profile updated successfully.',
    admin_customers_update_fail: 'Failed to update customer profile.',
    admin_customers_col_name: 'Customer Name',
    admin_customers_col_contact: 'Contact details',
    admin_customers_col_address: 'Delivery Address',
    admin_customers_col_segment: 'Segment',
    admin_customers_col_orders: 'Orders placed',
    admin_customers_col_spent: 'Total Spent',
    admin_customers_loading: 'Loading Client Database...',
    admin_customers_title: 'Customer Database',
    admin_customers_subtitle: 'View client purchase history, segmentation, and add notes',
    admin_customers_search: 'Search customers by name, phone...',
    admin_customers_empty: 'No customer records logged yet.',
    admin_customers_edit_title: 'Edit Customer Profile',
    admin_customers_edit_subtitle: 'Metadata editor',
    admin_customers_client_name: 'Client Name:',
    admin_customers_phone: 'Phone Number:',
    admin_customers_orders_placed: 'Orders Placed:',
    admin_customers_total_spent: 'Total Spent:',
    admin_customers_segment_label: 'Customer Segment',
    admin_customers_segment_new: 'New',
    admin_customers_segment_regular: 'Regular',
    admin_customers_segment_vip: 'VIP',
    admin_customers_comments_label: 'Special Comments / Sizing Details',
    admin_customers_comments_placeholder: 'e.g. Blazer size M, prefers wool blends, preferred courier...',
    admin_customers_cancel: 'Cancel',
    admin_customers_saving: 'Saving...',
    admin_customers_save: 'Save Profile',

    // Settings
    admin_settings_success: 'Global store configurations saved successfully.',
    admin_settings_fail: 'Failed to update store settings.',
    admin_settings_access_denied: 'Access Denied',
    admin_settings_access_desc: 'Only Super Administrators have access to modify global store settings.',
    admin_settings_loading: 'Loading Configuration Profiles...',
    admin_settings_title: 'Store Settings',
    admin_settings_subtitle: 'Configure taxes, local delivery costs, boutique details, and banking information',
    admin_settings_save: 'Save Settings',
    admin_settings_saving: 'Saving...',
    admin_settings_boutique: 'Boutique Details',
    admin_settings_store_name: 'Store Display Name',
    admin_settings_contact_email: 'Contact Email Address',
    admin_settings_contact_phone: 'Showroom Contact Phone',
    admin_settings_address: 'Showroom Address',
    admin_settings_payments: 'Payment Integrations',
    admin_settings_cod: 'Cash on Delivery',
    admin_settings_card: 'Card on Delivery',
    admin_settings_bank: 'Bank Transfer',
    admin_settings_bank_details: 'Showroom Bank Accounts (Details printed on Invoices)',
    admin_settings_hero: 'Hero Banner Images',
    admin_settings_hero_desc: 'Upload images to display in the main landing page hero carousel.',
    admin_settings_draft: 'Draft',
    admin_settings_add: 'Add',
    admin_settings_social: 'Social Network Coordinates',
    admin_settings_ig: 'Instagram Page Link',
    admin_settings_fb: 'Facebook Page Link',
    admin_settings_pin: 'Pinterest Coordinates',
    admin_settings_logistics: 'Shipping Logistics',
    admin_settings_tbilisi_fee: 'Tbilisi Local Delivery Fee (GEL)',
    admin_settings_regional_fee: 'Regional/Out-of-Town Delivery Fee (GEL)',
    admin_settings_min_free: 'Min Order value for Free Delivery (GEL)',
    admin_settings_tax_title: 'Tax Settings',
    admin_settings_vat: 'VAT Tax Rate (%)',
    admin_settings_tax_included: 'Taxes are included in displayed pricing',

    // Media
    admin_media_upload_success: 'File uploaded successfully.',
    admin_media_upload_fail: 'Failed to upload file.',
    admin_media_upload_error: 'Error communicating with media API.',
    admin_media_copied: 'Media URL copied to clipboard: ',
    admin_media_title: 'Media Library',
    admin_media_subtitle: 'Store, organize, and copy image links for products and content',
    admin_media_upload_btn: 'Upload File',
    admin_media_uploading: 'Uploading...',
    admin_media_dirs: 'Library Directories',
    admin_media_all: 'All',
    admin_media_search: 'Search assets by file name...',
    admin_media_loading: 'Loading Media Vault...',
    admin_media_empty: 'No media files matched your search.',
    admin_media_copy_link: 'Copy Link Path',

    // Marketing
    admin_marketing_title: 'Marketing & Discounts',
    admin_marketing_subtitle: 'Create promotional coupons, define flash discounts, and review usage',
    admin_marketing_create: 'Create Coupon',
    admin_marketing_create_sub: 'Define promotional offer parameters',
    admin_marketing_code: 'Coupon Code *',
    admin_marketing_type: 'Discount Type',
    admin_marketing_perc: 'Percentage (%)',
    admin_marketing_flat: 'Flat (GEL)',
    admin_marketing_val: 'Discount Value *',
    admin_marketing_exp: 'Expiration Date',
    admin_marketing_limit: 'Usage Limit (optional)',
    admin_marketing_btn: 'Create Coupon',
    admin_marketing_creating: 'Creating...',
    admin_marketing_active: 'Active Coupons',
    admin_marketing_active_sub: 'Review active promotional codes and usage status',
    admin_marketing_col_code: 'Code',
    admin_marketing_col_disc: 'Discount',
    admin_marketing_col_usage: 'Usage status',
    admin_marketing_col_exp: 'Expires',
    admin_marketing_col_status: 'Status',
    admin_marketing_col_action: 'Action',
    admin_marketing_no_coupons: 'No coupons registered.',
    admin_marketing_off: 'OFF',
    admin_marketing_uses: 'uses',
    admin_marketing_never: 'Never',
    admin_marketing_stat_act: 'Active',
    admin_marketing_stat_exp: 'Expired/Inactive',
    admin_marketing_disable: 'Disable',
    admin_marketing_enable: 'Enable',
    admin_marketing_err_req: 'Please fill out all required parameters correctly.',
    admin_marketing_succ: 'Discount coupon created successfully.',
    admin_marketing_fail: 'Failed to create discount coupon.',
    admin_marketing_err_net: 'Network error creating coupon.',
    admin_marketing_err_load: 'Failed to load coupon list.',
    admin_marketing_err_upd: 'Error updating coupon.',
    admin_marketing_err_act: 'Failed to change coupon active status.',
    admin_marketing_loading: 'Loading Marketing Center...',

    // Analytics
    admin_analytics_title: 'Business Analytics',
    admin_analytics_sub: 'Store traffic statistics, best sellers, and conversion parameters',
    admin_analytics_load: 'Loading Business Analytics...',
    admin_analytics_err: 'Failed to load business analytics.',
    admin_analytics_30d: 'Last 30 Days',
    admin_analytics_6m: 'Last 6 Months',
    admin_analytics_1y: 'Last Year',
    admin_analytics_dl: 'Download Report',
    admin_analytics_rev_vol: 'Revenue Generation & Order Volume',
    admin_analytics_rev_sub: 'Compare monthly orders vs revenue',
    admin_analytics_cat: 'Sales by Category',
    admin_analytics_cat_sub: 'Revenue distribution per category',
    admin_analytics_traffic: 'Storefront Traffic',
    admin_analytics_traffic_sub: 'Mocked visitors and browser views overview',
    admin_analytics_visitors: 'Total Visitors',
    admin_analytics_pageviews: 'Page Views',
    admin_analytics_conv: 'Conversion Rate',
    admin_analytics_bounce: 'Bounce Rate',
    admin_analytics_channel: 'Channel Performance',
    admin_analytics_channel_sub: 'Incoming traffic channels breakdown',
    admin_analytics_dresses: 'Dresses',
    admin_analytics_suits: 'Suits',
    admin_analytics_knitwear: 'Knitwear',
    admin_analytics_direct: 'Direct',
    admin_analytics_organic: 'Organic Search',
    admin_analytics_ig: 'Instagram Referral',
    admin_analytics_email: 'Email Campaign',

    // Content
    admin_content_title: 'Content Editor',
    admin_content_sub: 'Modify banner texts, FAQ database, and write blog articles',
    admin_content_load: 'Loading Content Editor...',
    admin_content_err: 'Failed to load storefront content configurations.',
    admin_content_save_succ: 'Storefront landing configuration saved successfully.',
    admin_content_save_fail: 'Failed to save settings.',
    admin_content_save_net: 'Network error saving config.',
    admin_content_blog_req: 'Please fill out all blog details.',
    admin_content_blog_succ: 'Blog entry published successfully.',
    admin_content_blog_fail: 'Failed to publish blog.',
    admin_content_blog_err: 'Error publishing blog.',
    admin_content_top_header: 'Top Header Promo Banner',
    admin_content_active: 'Active',
    admin_content_banner_text: 'Banner Notification Text',
    admin_content_hero: 'Hero Section Branding',
    admin_content_hero_title: 'Hero Title',
    admin_content_hero_sub: 'Hero Subtitle',
    admin_content_hero_desc: 'Branding Short Description',
    admin_content_save_config: 'Save Store Configurations',
    admin_content_pub_blog: 'Publish Blog Entry',
    admin_content_blog_title_en: 'Blog Title (English) *',
    admin_content_blog_title_ka: 'Title (Georgian)',
    admin_content_blog_slug: 'Blog Url Slug *',
    admin_content_blog_img: 'Blog Image Cover Path',
    admin_content_blog_body: 'Blog Body Content (Markdown supported) *',
    admin_content_pub_art: 'Publish Article',
    admin_content_act_art: 'Active Articles',
    admin_content_no_art: 'No articles written yet.',
  },
  GE: {
    // Navigation
    collections: 'კოლექციები',
    our_story: 'ჩვენი ისტორია',
    shop_the_look: 'სტილი',
    visit_us: 'გვეწვიეთ',
    call_us: 'დაგვიკავშირდით',
    shopping_cart: 'კალათა',

    // Hero
    handcrafted_luxury: 'ხელნაკეთი ფუფუნება',
    hero_title: 'VELLUTO',
    hero_subtitle: 'საუკეთესო ოსტატობის ხელოვნება',
    hero_desc:
      'აღმოაჩინეთ მარადიული დახვეწილი ტანსაცმლისა და მოდის კოლექციები, რომლებიც ხაზს უსვამს თქვენს ელეგანტურობას.',
    explore_collection: 'კოლექციის ნახვა',
    shop_look: 'სტილის ნახვა',

    // Editorial Intro
    heritage_title: 'მემკვიდრეობა',
    heritage_subtitle: 'შექმნილი მემკვიდრეობით, დახვეწილი დღევანდელობისთვის',
    heritage_desc1:
      'ქართველი მკერავებისა და მოდელიორების ხაზიდან წამოსული Velluto აერთიანებს თერძობის საგვარეულო ტექნიკასა და თანამედროვე მაღალი მოდის გეომეტრიას. თითოეული ნამუშევარი იქმნება ჩვენს თბილისის სახელოსნოში, პრემიუმ კლასის ქსოვილების გამოყენებით.',
    heritage_desc2:
      'ჩვენ გვჯერა, რომ ტანსაცმელი არ არის უბრალო აქსესუარი, არამედ თქვენი ხასიათის ფიზიკური გაგრძელებაა. მდუმარე დიალოგი ფორმას, ქსოვილსა და დიზაინს შორის.',
    stats_years: '12+',
    stats_years_label: 'წლის გამოცდილება',
    stats_items: '5,000+',
    stats_items_label: 'ხელნაკეთი ქმნილება',

    // Editorial Strip
    strip_title: 'ესთეტიკური განაცხადი',
    strip_subtitle: '"სილამაზე იწყება მაშინ, როდესაც გადაწყვეტთ იყოთ საკუთარი თავი."',
    strip_collection: 'საკუთარი ხელწერა',

    // New Arrivals
    new_arrivals: 'ახალი მოდელები',
    arrivals_subtitle: 'ჩვენი სახელოსნოს ბოლო კოლექციიდან საგულდაგულოდ შერჩეული სამოსი',
    add_to_cart: 'კალათაში დამატება',
    in_cart: 'დამატებულია',
    gel: 'ლარი',

    // Products
    product_ring_title: 'Velluto ოქროს ბეჭედი',
    product_ring_desc: 'ხელით გრავირებული 18k ყვითელი ოქროს ბეჭედი სუფთა გეომეტრიული ფასეტებით.',
    product_bracelet_title: 'ოქროს კლასიკური სამაჯური',
    product_bracelet_desc:
      'პრიალა მყარი ოქროს გადაჯაჭვული რგოლები, შექმნილი სინათლის იდეალურად ასარეკლად.',
    product_earrings_title: 'ბრილიანტის საყურეები',
    product_earrings_desc: 'ბრწყინვალე ჭრის VS1 ბრილიანტები, ჩასმული 18k თეთრ ოქროში.',

    // Shop the Look
    shop_look_title: 'სტილის ყიდვა',
    shop_look_subtitle:
      'მიიტანეთ კურსორი ოქროს წერტილებთან სტილის დეტალების დასათვალიერებლად და შესაძენად',
    spot_ring: 'Velluto ოქროს ბეჭედი — 2,400 ₾',
    spot_bracelet: 'ოქროს კლასიკური სამაჯური — 3,800 ₾',
    spot_earrings: 'ბრილიანტის საყურეები — 1,950 ₾',

    // Instagram
    insta_title: 'სარედაქციო გალერეა',
    insta_subtitle: 'თვალი ადევნეთ ჩვენს ყოველდღიურობასა და შთაგონებებს ინსტაგრამზე @velluto_____',

    // Location
    visit_us_title: 'ეწვიეთ ჩვენს ბუტიკს',
    visit_us_desc:
      'ჩვენი შოურუმი მდებარეობს თბილისის ისტორიულ უბანში. ეწვიეთ კოლექციების პირადად დასათვალიერებლად, მიიღეთ ზომის კონსულტაცია და ექსკლუზიურად ნახეთ ახალი მოდელები.',
    address_label: 'მისამართი',
    address_value: 'ვარდისუბანი, თბილისი, საქართველო',
    phone_label: 'ტელეფონი',
    hours_label: 'სამუშაო საათები',
    hours_value: 'ღიაა 24/7 · ორშ - კვირას (რეკომენდებულია წინასწარ ჩაწერა)',
    open_maps: 'რუკაზე ნახვა',

    // Footer
    footer_desc:
      'ექსკლუზიური ხელნაკეთი სამოსი და პრემიუმ აქსესუარები, რომლებიც შექმნილია თქვენი ინდივიდუალური სტილისთვის.',
    footer_copyright: 'ყველა უფლება დაცულია.',

    // Mini Cart
    cart_title: 'თქვენი არჩევანი',
    cart_empty: 'კალათა ცარიელია',
    cart_subtotal: 'ჯამი',
    cart_checkout: 'შეკვეთის გაფორმება',

    // Checkout
    checkout_title: 'უსაფრთხო შეკვეთა',
    checkout_subtitle: 'დაასრულეთ თქვენი შესყიდვა და გააფორმეთ შეკვეთა WhatsApp-ის საშუალებით',
    billing_details: 'მიწოდების დეტალები',
    full_name: 'სახელი და გვარი',
    phone_number: 'ტელეფონის ნომერი',
    order_notes: 'სპეციალური მოთხოვნები / ზომის შენიშვნა',
    notes_placeholder: 'მაგ: კაბის/პიჯაკის ზომის კორექტირება, მორგების დეტალები...',
    summary: 'შეკვეთის ჯამი',
    items_total: 'სამკაულების ჯამი',
    delivery: 'მიწოდება',
    free: 'უფასო',
    total_due: 'სულ გადასახდელი',
    complete_whatsapp: 'შეკვეთა WhatsApp-ით',
    whatsapp_error: 'გთხოვთ მიუთითოთ სახელი და ტელეფონის ნომერი.',
    back_to_shop: 'მაღაზიაში დაბრუნება',

    // Admin Panel
    admin_dashboard: 'მთავარი პანელი',
    admin_products: 'პროდუქტები',
    admin_orders: 'შეკვეთები',
    admin_customers: 'მომხმარებლები',
    admin_content: 'კონტენტის მართვა',
    admin_media: 'მედია ბიბლიოთეკა',
    admin_marketing: 'მარკეტინგი',
    admin_analytics: 'ანალიტიკა',
    admin_notifications: 'შეტყობინებები',
    admin_settings: 'პარამეტრები',
    admin_logout: 'გასვლა',
    admin_view_storefront: 'მაღაზიის ნახვა',
    admin_super_admin: 'მთავარი ადმინისტრატორი',
    admin_new_product_title: 'ახალი პროდუქტის დამატება',
    admin_new_product_subtitle: 'ფასის, აღწერის, ვარიანტების და SEO-ს განსაზღვრა',
    admin_cancel: 'გაუქმება',
    admin_add_product: 'დამატება',
    admin_saving: 'ინახება...',
    admin_prod_translations: 'პროდუქტის თარგმანები',
    admin_prod_name_en: 'პროდუქტის სახელი (EN) *',
    admin_prod_name_ka: 'პროდუქტის სახელი (KA) *',
    admin_prod_name_ru: 'პროდუქტის სახელი (RU) *',
    admin_desc_en: 'აღწერა (EN)',
    admin_desc_ka: 'აღწერა (KA)',
    admin_desc_ru: 'აღწერა (RU)',
    admin_pricing_logistics: 'ფასი და ლოგისტიკა',
    admin_base_price: 'საწყისი ფასი (₾) *',
    admin_sku: 'SKU კოდი *',
    admin_inventory: 'მარაგების რაოდენობა',
    admin_variants_title: 'პროდუქტის ვარიანტები',
    admin_add_variant: 'ვარიანტის დამატება',
    admin_no_variants: 'ვარიანტები არ არის. დაამატეთ ზომა ან ფერი.',
    admin_variant_sku: 'ვარიანტის SKU',
    admin_size: 'ზომა',
    admin_color: 'ფერი',
    admin_stock: 'მარაგი',
    admin_price_adj: 'ფასის კორექტირება (+/-)',
    admin_gallery_title: 'ფოტო გალერეა',
    admin_gallery_subtitle: 'აირჩიეთ ფოტოები მედია ბიბლიოთეკიდან',
    admin_upload_image: 'ფოტოს ატვირთვა',
    admin_uploading: 'იტვირთება...',
    admin_no_images: 'მედია ბიბლიოთეკაში ფოტოები არ მოიძებნა.',
    admin_status_tax: 'სტატუსი და კატეგორია',
    admin_prod_id: 'პროდუქტის ID (არასავალდებულო)',
    admin_category: 'კატეგორია *',
    admin_visibility: 'ხილვადობის სტატუსი',
    admin_promo_tag: 'პრომო ტეგი',
    admin_initial_rating: 'საწყისი შეფასება',
    admin_seo_config: 'SEO კონფიგურაცია',
    admin_seo_title: 'SEO სათაური',
    admin_seo_desc: 'SEO აღწერა',
    
    // Admin Dashboard
    admin_dashboard_loading: 'მონაცემების ჩატვირთვა...',
    admin_dashboard_retry: 'თავიდან ცდა',
    admin_dashboard_overview: 'მიმოხილვა',
    admin_dashboard_subtitle: 'მაღაზიის აქტივობები და მეტრიკები',
    admin_dashboard_refresh: 'განახლება',
    admin_stat_revenue: 'ჯამური შემოსავალი',
    admin_stat_orders: 'შესრულებული შეკვეთები',
    admin_stat_aov: 'შეკვეთის საშუალო ღირებულება',
    admin_stat_low_stock: 'მცირე მარაგების გაფრთხილება',
    admin_chart_title: 'ყოველთვიური გაყიდვების ანალიტიკა',
    admin_chart_subtitle: 'შემოსავლების გენერაციის დროის ხაზი',
    admin_chart_rendering: 'ჩარტის გენერაცია...',
    admin_recent_orders: 'ბოლო შეკვეთები',
    admin_recent_orders_sub: 'უახლესი შემოსული გაყიდვები',
    admin_view_all_orders: 'ყველა შეკვეთის ნახვა →',
    admin_table_id: 'ID',
    admin_table_customer: 'მომხმარებელი',
    admin_table_payment: 'გადახდა',
    admin_table_status: 'სტატუსი',
    admin_table_total: 'ჯამი',
    admin_no_recent_orders: 'ბოლო შეკვეთები არ მოიძებნა.',
    admin_best_sellers: 'ყველაზე გაყიდვადი პროდუქტები',
    admin_best_sellers_sub: 'ტოპ გაყიდვადი ნივთები',
    admin_no_sales: 'გაყიდვები ჯერ არ დაფიქსირებულა.',
    admin_qty_sold: 'გაყიდული რაოდენობა: ',
    admin_low_stock_warning: 'მარაგების გაფრთხილება',
    admin_low_stock_sub: 'ნივთები, რომლებსაც ესაჭიროებათ შევსება',
    admin_all_inventory_healthy: 'ყველა მარაგი წესრიგშია.',
    admin_left: 'დარჩენილია',
    
    // Admin Products List
    admin_products_loading: 'პროდუქტების კატალოგის ჩატვირთვა...',
    admin_products_title: 'პროდუქტების კატალოგი',
    admin_products_subtitle: 'მოძებნეთ, დაარედაქტირეთ და დააკოპირეთ პროდუქტები',
    admin_products_add: 'პროდუქტის დამატება',
    admin_products_search: 'მოძებნეთ პროდუქტები სახელით ან SKU-თი...',
    admin_products_empty: 'პროდუქტები ვერ მოიძებნა.',
    admin_products_image: 'ფოტო',
    admin_products_name_sku: 'სახელი და SKU',
    admin_products_category: 'კატეგორია',
    admin_products_price: 'ფასი',
    admin_products_inventory: 'მარაგი',
    admin_products_status: 'სტატუსი',
    admin_products_actions: 'მოქმედებები',
    admin_out_of_stock: 'მარაგი ამოიწურა',
    admin_units: 'ცალი',
    admin_product_dupe_success: 'პროდუქტი წარმატებით დაკოპირდა.',
    admin_product_dupe_fail: 'პროდუქტის კოპირება ვერ მოხერხდა.',
    admin_product_del_confirm: 'დარწმუნებული ხართ, რომ გსურთ პროდუქტის წაშლა? წაიშლება ყველა ვარიანტი და სურათი.',
    admin_product_del_success: 'პროდუქტი წარმატებით წაიშალა.',
    admin_product_del_fail: 'პროდუქტის წაშლა ვერ მოხერხდა.',

    // Edit Product
    admin_edit_product_title: 'პროდუქტის რედაქტირება',
    admin_edit_product_subtitle_staff: 'შეზღუდული რეჟიმი (მხოლოდ მარაგების განახლება)',
    admin_edit_product_subtitle_admin: 'მეტამონაცემების და ტაქსონომიის რედაქტირება SKU-სთვის: ',
    admin_edit_product_loading: 'პროდუქტის დეტალების ჩატვირთვა...',
    admin_edit_product_not_found: 'პროდუქტის დეტალები ვერ მოიძებნა.',
    admin_edit_product_success: 'პროდუქტი წარმატებით განახლდა.',
    admin_edit_product_fail: 'პროდუქტის განახლება ვერ მოხერხდა.',
    admin_save_changes: 'ცვლილებების შენახვა',

    // Orders List
    admin_orders_loading: 'შეკვეთების ჩატვირთვა...',
    admin_orders_no_export: 'საექსპორტო შეკვეთები არ მოიძებნა.',
    admin_orders_col_id: 'შეკვეთის ID',
    admin_orders_col_customer: 'მომხმარებელი',
    admin_orders_col_phone: 'ტელეფონი',
    admin_orders_col_address: 'მისამართი',
    admin_orders_col_date: 'მიწოდების თარიღი',
    admin_orders_col_time: 'მიწოდების დრო',
    admin_orders_col_method: 'მეთოდი',
    admin_orders_col_status: 'შეკვეთის სტატუსი',
    admin_orders_col_pay_status: 'გადახდის სტატუსი',
    admin_orders_col_total: 'ჯამური ფასი',
    admin_orders_col_items: 'შეკვეთილი ნივთები',
    admin_orders_filter_all_status: 'ყველა სტატუსი',
    admin_orders_filter_pending: 'მომლოდინე',
    admin_orders_filter_processing: 'მუშავდება',
    admin_orders_filter_shipped: 'გაგზავნილია',
    admin_orders_filter_delivered: 'მიწოდებულია',
    admin_orders_filter_cancelled: 'გაუქმებულია',
    admin_orders_filter_refunded: 'დაბრუნებულია',
    admin_orders_filter_all_pay: 'ყველა გადახდა',
    admin_orders_filter_cash: 'ნაღდი',
    admin_orders_filter_card: 'ბარათი',
    admin_orders_filter_bank: 'ბანკი',
    admin_orders_title: 'შეკვეთების ისტორია',
    admin_orders_subtitle: 'გაყიდვების და გადახდების მონიტორინგი',
    admin_orders_export: 'CSV ექსპორტი',
    admin_orders_search: 'მოძებნეთ სახელით, ID-თი, ტელეფონით...',
    admin_orders_empty: 'შეკვეთები ვერ მოიძებნა.',

    // Order Details
    admin_order_not_found: 'შეკვეთის დეტალები ვერ მოიძებნა.',
    admin_order_update_success: 'შეკვეთა წარმატებით განახლდა.',
    admin_order_update_fail: 'შეკვეთის განახლება ვერ მოხერხდა.',
    admin_order_loading: 'შეკვეთის ჩატვირთვა...',
    admin_order_title: 'შეკვეთის დეტალები',
    admin_order_subtitle: 'მართეთ შეკვეთის სტატუსი და დაბეჭდეთ ინვოისი',
    admin_order_view_invoice: 'ინვოისის ნახვა',
    admin_order_back: 'უკან დაბრუნება',
    admin_order_items: 'შეკვეთილი ნივთები',
    admin_order_options: 'არჩეული ვარიანტი: ',
    admin_order_qty: 'რაოდენობა: x',
    admin_order_subtotal: 'ჯამი',
    admin_order_discount: 'ფასდაკლების კოდი',
    admin_order_vat: 'დღგ (18% ჩათვლით)',
    admin_order_grand_total: 'სულ ჯამი',
    admin_order_notes: 'შენიშვნები',
    admin_order_no_notes: 'შეკვეთას არ აქვს შენიშვნა.',
    admin_order_actions: 'სტატუსის შეცვლა',
    admin_order_status_label: 'შეკვეთის სტატუსი',
    admin_order_payment_label: 'გადახდის სტატუსი',
    admin_order_unpaid: 'გადაუხდელი',
    admin_order_paid: 'გადახდილი',
    admin_order_updating: 'ახლდება...',
    admin_order_update_btn: 'სტატუსის განახლება',
    admin_order_client: 'მომხმარებლის პროფილი',
    admin_order_name: 'სახელი',
    admin_order_phone: 'ტელეფონი',
    admin_order_delivery_address: 'მისამართი',
    admin_order_delivery_schedule: 'მიწოდების გრაფიკი',
    admin_order_payment_option: 'გადახდის მეთოდი',
    admin_invoice_print: 'ინვოისის ბეჭდვა',
    admin_invoice_title: 'ინვოისი',
    admin_invoice_billed_to: 'გადამხდელი:',
    admin_invoice_boutique: 'ბუტიკის დეტალები:',
    admin_invoice_item_name: 'ნივთის სახელი',
    admin_invoice_variant_det: 'ვარიანტის დეტალები',
    admin_invoice_unit_price: 'ერთეულის ფასი',
    admin_invoice_coupon: 'კუპონი',

    // Customers List
    admin_customers_update_success: 'მომხმარებლის პროფილი წარმატებით განახლდა.',
    admin_customers_update_fail: 'მომხმარებლის პროფილის განახლება ვერ მოხერხდა.',
    admin_customers_col_name: 'სახელი',
    admin_customers_col_contact: 'საკონტაქტო დეტალები',
    admin_customers_col_address: 'მისამართი',
    admin_customers_col_segment: 'სეგმენტი',
    admin_customers_col_orders: 'შეკვეთები',
    admin_customers_col_spent: 'დახარჯული თანხა',
    admin_customers_loading: 'მომხმარებლების ჩატვირთვა...',
    admin_customers_title: 'მომხმარებლები',
    admin_customers_subtitle: 'ისტორიის და სეგმენტაციის მართვა',
    admin_customers_search: 'მოძებნეთ სახელით, ტელეფონით...',
    admin_customers_empty: 'მომხმარებლები არ მოიძებნა.',
    admin_customers_edit_title: 'პროფილის რედაქტირება',
    admin_customers_edit_subtitle: 'მეტამონაცემების რედაქტორი',
    admin_customers_client_name: 'კლიენტის სახელი:',
    admin_customers_phone: 'ტელეფონის ნომერი:',
    admin_customers_orders_placed: 'განთავსებული შეკვეთები:',
    admin_customers_total_spent: 'დახარჯული თანხა:',
    admin_customers_segment_label: 'მომხმარებლის სეგმენტი',
    admin_customers_segment_new: 'ახალი',
    admin_customers_segment_regular: 'რეგულარული',
    admin_customers_segment_vip: 'VIP',
    admin_customers_comments_label: 'სპეციალური შენიშვნები / ზომის დეტალები',
    admin_customers_comments_placeholder: 'მაგ. ატარებს M ზომას, უპირატესობას ანიჭებს შალს...',
    admin_customers_cancel: 'გაუქმება',
    admin_customers_saving: 'ინახება...',
    admin_customers_save: 'პროფილის შენახვა',

    // Settings
    admin_settings_success: 'კონფიგურაცია წარმატებით შეინახა.',
    admin_settings_fail: 'კონფიგურაციის შენახვა ვერ მოხერხდა.',
    admin_settings_access_denied: 'წვდომა აკრძალულია',
    admin_settings_access_desc: 'მხოლოდ სუპერ-ადმინისტრატორებს აქვთ პარამეტრების შეცვლის უფლება.',
    admin_settings_loading: 'პარამეტრების ჩატვირთვა...',
    admin_settings_title: 'მაღაზიის პარამეტრები',
    admin_settings_subtitle: 'გადასახადების, მიწოდების, ბუტიკის და ბანკის დეტალების მართვა',
    admin_settings_save: 'პარამეტრების შენახვა',
    admin_settings_saving: 'ინახება...',
    admin_settings_boutique: 'ბუტიკის დეტალები',
    admin_settings_store_name: 'მაღაზიის სახელი',
    admin_settings_contact_email: 'საკონტაქტო ელფოსტა',
    admin_settings_contact_phone: 'საკონტაქტო ტელეფონი',
    admin_settings_address: 'შოურუმის მისამართი',
    admin_settings_payments: 'გადახდის მეთოდები',
    admin_settings_cod: 'ნაღდი ანგარიშსწორება კურიერთან',
    admin_settings_card: 'ბარათით გადახდა კურიერთან',
    admin_settings_bank: 'საბანკო გადარიცხვა',
    admin_settings_bank_details: 'საბანკო ანგარიშის დეტალები (ინვოისისთვის)',
    admin_settings_hero: 'მთავარი ბანერის სურათები',
    admin_settings_hero_desc: 'ატვირთეთ სურათები მთავარი გვერდის კარუსელისთვის.',
    admin_settings_draft: 'დრაფტი',
    admin_settings_add: 'დამატება',
    admin_settings_social: 'სოციალური ქსელები',
    admin_settings_ig: 'Instagram-ის ბმული',
    admin_settings_fb: 'Facebook-ის ბმული',
    admin_settings_pin: 'Pinterest-ის ბმული',
    admin_settings_logistics: 'მიწოდების ლოგისტიკა',
    admin_settings_tbilisi_fee: 'მიწოდება თბილისში (ლარი)',
    admin_settings_regional_fee: 'მიწოდება რეგიონებში (ლარი)',
    admin_settings_min_free: 'უფასო მიწოდების მინიმალური შეკვეთა (ლარი)',
    admin_settings_tax_title: 'გადასახადები',
    admin_settings_vat: 'დღგ-ს განაკვეთი (%)',
    admin_settings_tax_included: 'გადასახადები შედის ნაჩვენებ ფასში',

    // Media
    admin_media_upload_success: 'ფაილი წარმატებით აიტვირთა.',
    admin_media_upload_fail: 'ფაილის ატვირთვა ვერ მოხერხდა.',
    admin_media_upload_error: 'დაფიქსირდა შეცდომა API-სთან კომუნიკაციისას.',
    admin_media_copied: 'მედიის ბმული დაკოპირდა: ',
    admin_media_title: 'მედია ბიბლიოთეკა',
    admin_media_subtitle: 'შეინახეთ და დააკოპირეთ სურათების ბმულები პროდუქტებისთვის',
    admin_media_upload_btn: 'ფაილის ატვირთვა',
    admin_media_uploading: 'იტვირთება...',
    admin_media_dirs: 'ბიბლიოთეკის დირექტორიები',
    admin_media_all: 'ყველა',
    admin_media_search: 'მოძებნეთ ფაილის სახელით...',
    admin_media_loading: 'მედიის ჩატვირთვა...',
    admin_media_empty: 'მედია ფაილები ვერ მოიძებნა.',
    admin_media_copy_link: 'ბმულის კოპირება',

    // Marketing
    admin_marketing_title: 'მარკეტინგი და ფასდაკლებები',
    admin_marketing_subtitle: 'შექმენით პრომო კოდები და აკონტროლეთ გამოყენება',
    admin_marketing_create: 'კუპონის შექმნა',
    admin_marketing_create_sub: 'განსაზღვრეთ პრომო შეთავაზების პარამეტრები',
    admin_marketing_code: 'კუპონის კოდი *',
    admin_marketing_type: 'ფასდაკლების ტიპი',
    admin_marketing_perc: 'პროცენტი (%)',
    admin_marketing_flat: 'ფიქსირებული (ლარი)',
    admin_marketing_val: 'ფასდაკლების მნიშვნელობა *',
    admin_marketing_exp: 'ვადის ამოწურვა',
    admin_marketing_limit: 'გამოყენების ლიმიტი (არასავალდებულო)',
    admin_marketing_btn: 'კუპონის შექმნა',
    admin_marketing_creating: 'იქმნება...',
    admin_marketing_active: 'აქტიური კუპონები',
    admin_marketing_active_sub: 'გადახედეთ აქტიურ პრომო კოდებს',
    admin_marketing_col_code: 'კოდი',
    admin_marketing_col_disc: 'ფასდაკლება',
    admin_marketing_col_usage: 'გამოყენება',
    admin_marketing_col_exp: 'ვადა',
    admin_marketing_col_status: 'სტატუსი',
    admin_marketing_col_action: 'მოქმედება',
    admin_marketing_no_coupons: 'კუპონები არ მოიძებნა.',
    admin_marketing_off: 'ფასდაკლება',
    admin_marketing_uses: 'ჯერ',
    admin_marketing_never: 'არასდროს',
    admin_marketing_stat_act: 'აქტიური',
    admin_marketing_stat_exp: 'ვადაგასული/არააქტიური',
    admin_marketing_disable: 'გამორთვა',
    admin_marketing_enable: 'ჩართვა',
    admin_marketing_err_req: 'გთხოვთ, შეავსოთ ყველა აუცილებელი ველი.',
    admin_marketing_succ: 'კუპონი წარმატებით შეიქმნა.',
    admin_marketing_fail: 'კუპონის შექმნა ვერ მოხერხდა.',
    admin_marketing_err_net: 'ქსელის შეცდომა კუპონის შექმნისას.',
    admin_marketing_err_load: 'კუპონების ჩატვირთვა ვერ მოხერხდა.',
    admin_marketing_err_upd: 'კუპონის განახლების შეცდომა.',
    admin_marketing_err_act: 'სტატუსის შეცვლა ვერ მოხერხდა.',
    admin_marketing_loading: 'მარკეტინგის ჩატვირთვა...',

    // Analytics
    admin_analytics_title: 'ბიზნეს ანალიტიკა',
    admin_analytics_sub: 'მაღაზიის ტრაფიკის სტატისტიკა და კონვერსია',
    admin_analytics_load: 'ბიზნეს ანალიტიკის ჩატვირთვა...',
    admin_analytics_err: 'ბიზნეს ანალიტიკის ჩატვირთვა ვერ მოხერხდა.',
    admin_analytics_30d: 'ბოლო 30 დღე',
    admin_analytics_6m: 'ბოლო 6 თვე',
    admin_analytics_1y: 'ბოლო წელი',
    admin_analytics_dl: 'რეპორტის გადმოწერა',
    admin_analytics_rev_vol: 'შემოსავლები და შეკვეთების მოცულობა',
    admin_analytics_rev_sub: 'ყოველთვიური შეკვეთებისა და შემოსავლების შედარება',
    admin_analytics_cat: 'გაყიდვები კატეგორიების მიხედვით',
    admin_analytics_cat_sub: 'შემოსავლების განაწილება',
    admin_analytics_traffic: 'მაღაზიის ტრაფიკი',
    admin_analytics_traffic_sub: 'ვიზიტორების და ნახვების მიმოხილვა',
    admin_analytics_visitors: 'ვიზიტორები სულ',
    admin_analytics_pageviews: 'გვერდის ნახვები',
    admin_analytics_conv: 'კონვერსია',
    admin_analytics_bounce: 'Bounce Rate',
    admin_analytics_channel: 'არხების ეფექტურობა',
    admin_analytics_channel_sub: 'შემომავალი ტრაფიკის არხების განაწილება',
    admin_analytics_dresses: 'კაბები',
    admin_analytics_suits: 'კოსტიუმები',
    admin_analytics_knitwear: 'ნაქსოვი ტანსაცმელი',
    admin_analytics_direct: 'პირდაპირი',
    admin_analytics_organic: 'ორგანული ძიება',
    admin_analytics_ig: 'Instagram',
    admin_analytics_email: 'Email კამპანია',

    // Content
    admin_content_title: 'კონტენტის მართვა',
    admin_content_sub: 'შეცვალეთ ბანერის ტექსტები და დაამატეთ ბლოგები',
    admin_content_load: 'კონტენტის რედაქტორის ჩატვირთვა...',
    admin_content_err: 'კონტენტის კონფიგურაციის ჩატვირთვა ვერ მოხერხდა.',
    admin_content_save_succ: 'კონფიგურაცია წარმატებით შეინახა.',
    admin_content_save_fail: 'პარამეტრების შენახვა ვერ მოხერხდა.',
    admin_content_save_net: 'ქსელის შეცდომა პარამეტრების შენახვისას.',
    admin_content_blog_req: 'გთხოვთ, შეავსოთ ბლოგის ყველა დეტალი.',
    admin_content_blog_succ: 'ბლოგი წარმატებით გამოქვეყნდა.',
    admin_content_blog_fail: 'ბლოგის გამოქვეყნება ვერ მოხერხდა.',
    admin_content_blog_err: 'შეცდომა ბლოგის გამოქვეყნებისას.',
    admin_content_top_header: 'მთავარი პრომო ბანერი',
    admin_content_active: 'აქტიური',
    admin_content_banner_text: 'ბანერის ტექსტი',
    admin_content_hero: 'მთავარი სექციის ტექსტები',
    admin_content_hero_title: 'მთავარი სათაური',
    admin_content_hero_sub: 'ქვესათაური',
    admin_content_hero_desc: 'მოკლე აღწერა',
    admin_content_save_config: 'კონფიგურაციის შენახვა',
    admin_content_pub_blog: 'ბლოგის გამოქვეყნება',
    admin_content_blog_title_en: 'ბლოგის სათაური (EN) *',
    admin_content_blog_title_ka: 'სათაური (GE)',
    admin_content_blog_slug: 'ბლოგის URL Slug *',
    admin_content_blog_img: 'ფოტოს ბმული',
    admin_content_blog_body: 'ბლოგის შინაარსი (Markdown) *',
    admin_content_pub_art: 'სტატიის გამოქვეყნება',
    admin_content_act_art: 'აქტიური სტატიები',
    admin_content_no_art: 'სტატიები ჯერ არ არის.',
  },
  RU: {
    // Navigation
    collections: 'Коллекции',
    our_story: 'Наша история',
    shop_the_look: 'Образ',
    visit_us: 'Контакты',
    call_us: 'Позвонить',
    shopping_cart: 'Корзина',

    // Hero
    handcrafted_luxury: 'Роскошь ручной работы',
    hero_title: 'VELLUTO',
    hero_subtitle: 'Искусство тонкого мастерства',
    hero_desc:
      'Откройте для себя коллекции изысканной одежды и премиальной моды, созданных подчеркнуть вашу элегантность.',
    explore_collection: 'Смотреть коллекцию',
    shop_look: 'Купить образ',

    // Editorial Intro
    heritage_title: 'НАСЛЕДИЕ',
    heritage_subtitle: 'Скульптурные традиции, современная эстетика',
    heritage_desc1:
      'Происходя из династии грузинских мастеров портного искусства, Velluto сочетает традиционные методы пошива с геометрией высокой моды. Каждое изделие создается вручную в нашей тбилисской мастерской из премиальных тканей.',
    heritage_desc2:
      'Мы верим, что одежда — это не просто аксессуар, а физическое продолжение вашего характера. Безмолвный диалог между формой, материалом и дизайном.',
    stats_years: '12+',
    stats_years_label: 'Лет мастерства',
    stats_items: '5,000+',
    stats_items_label: 'Уникальных изделий',

    // Editorial Strip
    strip_title: 'Эстетический манифест',
    strip_subtitle: '"Красота начинается в тот момент, когда вы решаете быть собой."',
    strip_collection: 'Фирменная коллекция',

    // New Arrivals
    new_arrivals: 'Новинки',
    arrivals_subtitle: 'Особые знаковые модели из последнего выпуска нашей мастерской',
    add_to_cart: 'Добавить в корзину',
    in_cart: 'Добавлено',
    gel: 'GEL',

    // Products
    product_ring_title: 'Золотое кольцо-печатка Velluto',
    product_ring_desc:
      'Выгравированное вручную кольцо из желтого золота 18k с чистыми геометрическими гранями.',
    product_bracelet_title: 'Фактурный золотой браслет',
    product_bracelet_desc:
      'Полированные звенья из цельного золота, созданные улавливать свет под любым углом.',
    product_earrings_title: 'Серьги-пусеты с бриллиантами',
    product_earrings_desc: 'Бриллианты круглой огранки VS1 в оправе из белого золота 18k.',

    // Shop the Look
    shop_look_title: 'Купить образ',
    shop_look_subtitle: 'Наведите курсор на золотые точки, чтобы рассмотреть детали образа',
    spot_ring: 'Золотое кольцо-печатка Velluto — 2,400 GEL',
    spot_bracelet: 'Фактурный золотой браслет — 3,800 GEL',
    spot_earrings: 'Серьги-пусеты с бриллиантами — 1,950 GEL',

    // Instagram
    insta_title: 'Галерея образов',
    insta_subtitle: 'Следите за нашими новостями и вдохновением в Instagram @velluto_____',

    // Location
    visit_us_title: 'Посетите наш бутик',
    visit_us_desc:
      'Наш шоурум расположен в историческом районе Тбилиси. Оцените коллекции лично, получите консультацию по подбору размера и ознакомьтесь с новинками.',
    address_label: 'Адрес',
    address_value: 'Вардисубани, Тбилиси, Грузия',
    phone_label: 'Телефон',
    hours_label: 'Часы работы',
    hours_value: 'Открыто 24/7 · Пн - Вс (рекомендуется предварительная запись)',
    open_maps: 'Открыть на картах',

    // Footer
    footer_desc:
      'Эксклюзивная одежда ручной работы и премиальные аксессуары, созданные для выражения вашего стиля.',
    footer_copyright: 'Все права защищены.',

    // Mini Cart
    cart_title: 'Ваш выбор',
    cart_empty: 'Ваша корзина пуста',
    cart_subtotal: 'Итого',
    cart_checkout: 'Оформить заказ',

    // Checkout
    checkout_title: 'Оформление заказа',
    checkout_subtitle: 'Подтвердите свой выбор и завершите оформление заказа в WhatsApp',
    billing_details: 'Детали доставки бутика',
    full_name: 'Имя и фамилия',
    phone_number: 'Номер телефона',
    order_notes: 'Особые пожелания / Размер кольца',
    notes_placeholder: 'Например, регулировка размера платья/костюма, особенности кроя...',
    summary: 'Сводка заказа',
    items_total: 'Стоимость изделий',
    delivery: 'Доставка',
    free: 'Бесплатно',
    total_due: 'Итого к оплате',
    complete_whatsapp: 'Завершить заказ в WhatsApp',
    whatsapp_error: 'Пожалуйста, заполните имя и телефон.',
    back_to_shop: 'Вернуться в магазин',

    // Admin Panel
    admin_dashboard: 'Панель управления',
    admin_products: 'Товары',
    admin_orders: 'Заказы',
    admin_customers: 'Клиенты',
    admin_content: 'Редактор контента',
    admin_media: 'Медиатека',
    admin_marketing: 'Маркетинг',
    admin_analytics: 'Аналитика',
    admin_notifications: 'Уведомления',
    admin_settings: 'Настройки',
    admin_logout: 'Выйти',
    admin_view_storefront: 'Просмотр магазина',
    admin_super_admin: 'Супер Админ',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('EN');

  // Load language preference from localStorage on mount
  useEffect(() => {
    const savedLang = localStorage.getItem('velluto_language');
    if (savedLang && (savedLang === 'EN' || savedLang === 'GE' || savedLang === 'RU')) {
      setLanguageState(savedLang as Language);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('velluto_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['EN'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
